Document: scientific-word
Title: Debian scientific-word Manual
Author: <insert document author here>
Abstract: This manual describes what scientific-word is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/scientific-word/scientific-word.sgml.gz

Format: postscript
Files: /usr/share/doc/scientific-word/scientific-word.ps.gz

Format: text
Files: /usr/share/doc/scientific-word/scientific-word.text.gz

Format: HTML
Index: /usr/share/doc/scientific-word/html/index.html
Files: /usr/share/doc/scientific-word/html/*.html
